name: Publish to NuGet

on:
  push:
    tags:
    - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.200

      - name: Build and publish
        run: |
          dotnet pack -o output src/DotNetSdkHelpers/DotNetSdkHelpers.csproj
          dotnet nuget push output/ -s https://nuget.org -k ${NUGET_API_KEY}
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
